config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root  "home#index"
  get 'random_shirt', to: 'random_shirt#random'
  resources :shirts do
    resources :notes, only: :create
  end

  get '/sign-up', to: 'registrations#new'
  post '/sign-up', to: 'registrations#create'

  get '/sign-in', to: 'sessions#new'
  post '/sign-in', to: 'sessions#create'
  delete '/sign-out', to: 'sessions#destroy', as: 'sign_out'

  resources :ownerships, only: [:create, :destroy]
end

app/models/label.rb
class Label < ActiveRecord::Base
  belongs_to :shirt
  belongs_to :tag
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :shirt
  belongs_to :author, foreign_key: :user_id, class_name: User
end

app/models/ownership.rb
class Ownership < ActiveRecord::Base
  belongs_to :user
  belongs_to :shirt
  validates :shirt_id, uniqueness: {scope: :user_id, message: "is already in your collection"}
end

app/models/shirt.rb
class Shirt < ActiveRecord::Base
  has_many :labels
  has_many :tags, through: :labels
  has_many :ownerships # user_id, shirt_id
  has_many :owners, through: :ownerships, source: :user
  has_many :notes
  has_many :commenters, through: :notes, source: :user
  accepts_nested_attributes_for :tags, reject_if: -> (attributes){attributes[:name].blank?}
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :labels
  has_many :shirts, through: :labels
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :ownerships
  has_many :shirts, through: :ownerships
  has_many :notes

  recommends :shirts

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?
  before_action :authenticate!

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def authenticate!
    redirect_to root_path, notice: "You must be logged in to do that" unless logged_in?
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_filter :authenticate!
  def index
  	@shirts = Shirt.all
    render "page", :layout => false
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def create
    save_note = params.require(:note).permit(:content)
    shirt = Shirt.find(params[:shirt_id])
    shirt.notes.create(save_note.merge(author: current_user))
    redirect_to shirt
  end
end

app/controllers/ownerships_controller.rb
class OwnershipsController < ApplicationController
  def create
    shirt = Shirt.find(params[:shirt_id])
    current_user.shirts << shirt
    current_user.like(shirt)
    @recommendations  = current_user.recommended_shirts(4)
    
    respond_to do |format|
      format.html { redirect_to shirt}
      format.js { render :template => "/shirts/create.js.erb" }
    end
   
  end
end

# respond_to do |format|
#       format.html { redirect_to shirt}
#       format.js {  }
#     end

app/controllers/random_shirt_controller.rb
class RandomShirtController < ApplicationController
  skip_before_action :authenticate!
  def random
    random_site = ["http://riptapparel.com", "http://teefury.com", 'http://shirt.woot.com'].sample
    redirect_to random_site
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  skip_before_action :authenticate!
  def new
    @user = User.new
  end

  def create
    user_params = params.require(:user).permit(:email, :password, :password_confirmation)
    @user = User.new(user_params)
    if @user.save
      session[:user_id]  = @user.id
      redirect_to root_url, notice: "Your account has been created!"
    else
      render :new
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :boot_if_logged_in, except: :destroy
  skip_before_action :authenticate!
  def new
    @user = User.new
  end

  def create
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path, notice: "You've been signed in"
    else
      @user.errors[:base] = "Bad username or password"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "You have been successfully signed out!"
  end

  private
  def boot_if_logged_in
    redirect_to root_path if logged_in?
  end
end

app/controllers/shirts_controller.rb
class ShirtsController < ApplicationController
  skip_before_action :authenticate!, only: [:index, :show]
  def index
    @shirts = Shirt.all
  end

  def show
    @shirt = Shirt.find(params[:id])
    @recommendations  = current_user.recommended_shirts(4)
    
    respond_to do |format|
      format.json { render json: @shirt }
      format.xml { render xml: @shirt }
      format.html
    end
  end

  def new
    @shirt = Shirt.new
  end

  def create
    @shirt = Shirt.create(safe_params)
    redirect_to @shirt
  end

  def edit
    @shirt = Shirt.find(params[:id])
  end

  def update
    @shirt = Shirt.find(params[:id])
    @shirt.update(safe_params)
    redirect_to @shirt
  end

  private
  def safe_params
    safe_params = params.require(:shirt).permit(:name, :url, tag_ids: [], tags_attributes: [:name])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/ownerships_helper.rb
module OwnershipsHelper
end

app/helpers/random_shirt_helper.rb
module RandomShirtHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shirts_helper.rb
module ShirtsHelper
end

app/views/home/page.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShirtHappens</title>
  <link href='http://fonts.googleapis.com/css?family=Special+Elite' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>




</head>
<body id="home">
<div class="container-fluid">
  <main> <!-- class="fcontainer" -->
    

    <div class="all-content">
      <nav class="user">
          <ul>
            <% if logged_in? %>
               <li>Hey, <%= current_user.email %></li>
               <li><%= link_to "Sign out", sign_out_path, method: :delete %></li>
             <% else %>
               <li><%= link_to "Sign up", sign_up_path %></li>
               <li><%= link_to "Sign in", sign_in_path %></li>
             <% end %>
            </ul>
      </nav>
      <section class="banner"><!-- skewed -->
        <h1>Shirt Happens</h1>
        <h2>You are what you wear</h2>
      </section>
      <nav class="views"> 
        <div class="redbtn"> 
          Scroll Down <span class="glyphicon glyphicon-arrow-down" aria-hidden="true"></span>
        </div>
      </nav> 
    </div><!-- all-content -->

    <section class="gallery-container">
      <ul class='row gallery-list'>
        <%= render partial: '/shirts/shirt', collection: @shirts %>
      </ul>
    </section><!-- gallery-container -->
  </main>
</div><!-- container -->

</body>
</html>

app/views/shirts/_form.html.erb
<%= form_for @shirt do |f|%>
  <div class="name">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="url">
    <%= f.label :url %>
    <%= f.url_field :url %>
  </div>
  <div class="tags row">
    <%= f.collection_check_boxes :tag_ids, Tag.all, :id, :name do |tag| %>
      <div class="col-xs-2">
        <%= tag.check_box %>
        <%= tag.label %>
      </div>
    <% end %>
  </div>
  <div class="tag_name row">
    <%= f.fields_for :tags, Tag.new do |tag_form| %>
      <%= tag_form.label :name %>
      <%= tag_form.text_field :name %>
    <% end %>
  </div>
  <%= f.submit %>
<% end %>

app/views/shirts/_recommendations.html.erb
    <% @recommendations.each do |item| %>
      <li class='col-xs-3'>
          <div class="shirt-container">
            <a href="/shirts/<%=item.id %>" >
            <span class="frame frame-sm"><span></span></span>
            <%= image_tag item.image_url, class: 'img-responsive' %>
            </a>
          </div>
          <div class="shirt-heading"> 
            <%= link_to item.name, shirt_path(item) %>
          </div>
        </li>
      <% end %>
    </ul>   

 

app/views/shirts/_shirt.html.erb
<li class='col-xs-3 gallery element'>

    
    <%= link_to shirt do %>
    	<div class="shirt-container">
    		<span class="frame frame-sm"><span></span></span>
      	<%= image_tag shirt.image_url, class: 'img-responsive'%>
      </div>
      <div class="shirt-heading">
      <%= truncate shirt.name, length: 30 %>
    </div>
    <% end %>
    
    
</li>

app/views/shirts/create.js.erb
debugger;
//remove add to collection link
$('#addCollection').addClass('slide-out');
//scroll down
$('html,body').animate({
  scrollTop: $('#shirt').offset().top
        }, 1000);
//


$('.new-rc ul').append("<%= j render @recommendations %>");



$('.new-rc').fadeIn(1000);
   

app/views/shirts/edit.html.erb
<h1>Edit this shirt</h1>
<%= render 'form' %>
<h2>
<%= link_to "Remove from your collection", ownerships_path(shirt_id: @shirt.id), method: :delete %>
</h2>

app/views/shirts/index.html.erb
<main>
	<h1>Shirts</h1>
	  <section class='row'>
	    <%= render @shirts %>
	  </section>
	<nav class="views">
	  <% if logged_in? %>
	    <%= link_to "Create a new shirt",  new_shirt_path %>
	  <% end %>
	</nav>
</main>

app/views/shirts/new.html.erb
<h1>Create a new shirt</h1>
<%= render 'form' %>

app/views/shirts/show.html.erb
<main>
  <div class="container">
    <section id="shirt" class="row">
      <div class="info col-md-6 offset-md-1">
        <h1><%= @shirt.name %></h1>
        <h2>by <%= @shirt.artist %></h2>
        <nav class="views">
          <ul>
           <li><%= link_to "<< Back to Shirts Menu", shirts_path %></li>
            <% if logged_in? %>
              <li><%= link_to "Edit this shirt >>", edit_shirt_path(@shirt) %></li>
            <% end %>
            
            <% if logged_in? && !current_user.likes?(@shirt) %>
              <li><%= link_to "Add to your collection", ownerships_path(shirt_id: @shirt.id), method: :post, remote: :true, id: :addCollection %></li>
            <% end %>
          </ul>
        </nav>
      </div>
      <div class="shirt-container col-md-5">
      <span class="frame frame775"><span></span></span>
        <%= image_tag @shirt.image_url, class: 'img-responsive' %>
      </div>
    </section>
  </div>

  <section id="recommendations" class="banner">
    <div class="wrapper">
      <% if current_user.likes?(@shirt) %>
        <h2>You might also like this....</h2>
        <ul>
          <% @recommendations.each do |item| %>
            <li class='col-xs-3'>
              <div class="shirt-container">
                <a href="<%=shirt_path(item) %>">
                <span class="frame frame-sm"><span></span></span>
                <%= image_tag item.image_url, class: 'img-responsive' %></a>
              </div>
              <div class="shirt-heading">   
                <%= link_to item.name, shirt_path(item) %>
              </div>
            </li>
          <% end %>
        </ul>
      <% else %>
        <div class="new-rc">
          <h2>You might also like this....</h2>
          <ul>
          </ul>
        </div>
      <% end %>
    </div>
  </section>

  
</main>